from google import genai


def generate_roadmap(client: genai.Client, prompt: str) -> str:
    """Generates a structured step-by-step learning path and roadmap using Gemini 3.8 Flash."""
    if not prompt or not prompt.strip():
        return "Please provide a topic or skill to generate a learning path."

    formatted_prompt = (
        "Create a comprehensive, step-by-step learning roadmap to master the following topic/skill.\n\n"
        "Formatting Instructions:\n"
        "- Break the roadmap down into clear chronological stages (e.g., Phase 1: Beginner, Phase 2: Intermediate, Phase 3: Advanced).\n"
        "- Include key topics, recommended project ideas, and estimated timelines for each phase.\n"
        "- Use bullet points and clear Markdown headers.\n\n"
        f"Topic/Skill:\n{prompt.strip()}"
    )

    try:
        chat = client.chats.create(model="gemini-3.8-flash")
        response = chat.send_message(formatted_prompt)

        if response and response.text:
            return response.text
        else:
            return "No roadmap content was generated by the model."

    except Exception as e:
        raise RuntimeError(f"Learning path generation failed: {str(e)}")