from google import genai


def get_answer(client: genai.Client, prompt: str) -> str:
    """Generates a detailed answer with examples using Gemini 3.8 Flash."""
    if not prompt or not prompt.strip():
        return "Please provide a valid question or prompt."

    formatted_prompt = (
        "Answer the following question clearly with detailed explanations "
        f"and practical examples:\n\n{prompt.strip()}"
    )

    try:
        chat = client.chats.create(model="gemini-3.8-flash")
        response = chat.send_message(formatted_prompt)

        if response and response.text:
            return response.text
        else:
            return "No response text was generated by the model."

    except Exception as e:
        raise RuntimeError(f"Q&A generation failed: {str(e)}")