from google import genai


def generate_quiz(client: genai.Client, prompt: str) -> str:
    """Generates a 3-question multiple-choice quiz with an answer key using Gemini 3.8 Flash."""
    if not prompt or not prompt.strip():
        return "Please provide a valid topic or content to generate a quiz."

    formatted_prompt = (
        "Generate a 3-question multiple-choice quiz based on the following topic/text.\n\n"
        "Formatting Instructions:\n"
        "- Format each question clearly with options labeled (A, B, C, D).\n"
        "- At the very end, include an 'Answer Key' section with brief explanations for each correct answer.\n\n"
        f"Topic/Content:\n{prompt.strip()}"
    )

    try:
        chat = client.chats.create(model="gemini-3.8-flash")
        response = chat.send_message(formatted_prompt)

        if response and response.text:
            return response.text
        else:
            return "No quiz content was generated by the model."

    except Exception as e:
        raise RuntimeError(f"Quiz generation failed: {str(e)}")