from google import genai


def summarize_text(client: genai.Client, prompt: str) -> str:
    """Summarizes text into key bullet points using Gemini 3.8 Flash."""
    if not prompt or not prompt.strip():
        return "Please provide text to summarize."

    formatted_prompt = (
        "Summarize the following text clearly and concisely.\n\n"
        "Formatting Guidelines:\n"
        "- Provide a brief 1-2 sentence overview first.\n"
        "- List the key takeaways as bullet points.\n"
        "- Keep the language simple and easy to understand.\n\n"
        f"Text to Summarize:\n{prompt.strip()}"
    )

    try:
        chat = client.chats.create(model="gemini-3.8-flash")
        response = chat.send_message(formatted_prompt)

        if response and response.text:
            return response.text
        else:
            return "No summary content was generated by the model."

    except Exception as e:
        raise RuntimeError(f"Summary generation failed: {str(e)}")